repos:
  - repo: http://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace


  - repo: http://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
